# Generated by Django 4.1.2 on 2022-10-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='complimentary_wifi_router',
            new_name='free_wifi_router',
        ),
    ]
