# Generated by Django 4.1.2 on 2022-10-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_complimentary_wifi_router_apartment_free_wifi_router'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='electricity',
            new_name='free_electricity',
        ),
    ]
