# Generated by Django 4.1.2 on 2022-10-15 21:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_electricity_apartment_free_electricity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(choices=[('Studio', 'Studio'), ('1 Bed', '1 Bed'), ('2 Bed', '2 Bed'), ('3 Bed', '3 Bed'), ('4 Bed or More', '4 Bed or More')], default='Studio', max_length=20)),
                ('current_year_data', models.IntegerField(default=0)),
                ('one_year_data', models.IntegerField(default=0)),
                ('two_year_data', models.IntegerField(default=0)),
                ('three_year_data', models.IntegerField(default=0)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_apartment', to='main.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_term', models.CharField(choices=[('2023-2024', '2023-2024'), ('2022-2023', '2022-2023'), ('2021-2022', '2021-2022'), ('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019'), ('2017-2018', '2017-2018'), ('2016-2017', '2016-2017'), ('2015-2016', '2015-2016'), ('2014-2015', '2014-2015'), ('2013-2014', '2013-2014'), ('2012-2013', '2012-2013'), ('2011-2012', '2011-2012'), ('2010-2011', '2010-2011'), ('2009-2010', '2009-2010'), ('2008-2009', '2008-2009'), ('2007-2008', '2007-2008'), ('2006-2007', '2006-2007'), ('2005-2006', '2005-2006'), ('2004-2005', '2004-2005'), ('2003-2004', '2003-2004'), ('2002-2003', '2002-2003'), ('2001-2002', '2001-2002'), ('2000-2001', '2000-2001')], default='2022-2023', max_length=20)),
                ('contract_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('lease_type', models.CharField(choices=[('One Year Lease', 'One Year Lease'), ('Sublet', 'Sublet')], default='One Year Lease', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('flat_type', models.CharField(choices=[('Studio', 'Studio'), ('1 Bed', '1 Bed'), ('2 Bed', '2 Bed'), ('3 Bed', '3 Bed'), ('4 Bed or More', '4 Bed or More')], default='Studio', max_length=20)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_apartment', to='main.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
