# Generated by Django 4.1.2 on 2022-10-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_statistics_leasedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='current_year_data',
        ),
    ]
